### PR TITLE
add node 16

### LINKED ISSUE #38: Add v16 image
We just had the case in our main web repo that CI runs with owncloud-ci docker images on v14 whilst we're locally developing on v15 (which reaches its official EOL in a couple of weeks), causing some hickups and the need for re-introducing old features/polyfilling. Would be cool if we could switch to v16 as it's the new `current` version?

Feel free to close this issue if not applicable

### PR DESCRIPTION
**Pull request by wkloucek**
fixes #38

### CODE REVIEW

**Comment by xoxys** [comment]
Is there a reason why we don't use the latest LTS more often? The `current` tree has quite short lifetime.

**Review by xoxys — APPROVED** [review]

**Comment by xoxys** [comment]
Especially as the CI was still running with node v12 a few  days ago, so looks like we don't need new features from the latest node version. Just curious why we need so many versions.

**Comment by pascalwengerter** [comment]
> Is there a reason why we don't use the latest LTS more often? The `current` tree has quite short lifetime.

At least in the Nodejs world [current turns into LTS](https://nodejs.org/en/about/releases/) so the lifespan of a version should be fine (nothing compared to a Ubuntu LTS or sth though, ofc)

**Comment by pascalwengerter** [comment]
> Especially as the CI was still running with node v12 a few days ago, so looks like we don't need new features from the latest node version. Just curious why we need so many versions.

Guess we're finally making some progress and have refactored things to a point where we're using what is considered "modern features" in the JS world 🤷🏽 with the `web` project being a focus now we can hopefully stay up-to-date in the future

**Comment by pascalwengerter** [comment]
> > Especially as the CI was still running with node v12 a few days ago, so looks like we don't need new features from the latest node version. Just curious why we need so many versions.
> 
> Guess we're finally making some progress and have refactored things to a point where we're using what is considered "modern features" in the JS world 🤷🏽 with the `web` project being a focus now we can hopefully stay up-to-date in the future

CI failures yesterday for example were because of a [standard JS method](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/replaceAll) that is supported in all major browsers already but not part of the Nodejs LTS (which is 14 atm)

**Pull request merged**
