### PR TITLE
add arm architectures, remove EOL node and base all on Ubuntu 18.04 LTS

### PR DESCRIPTION
**Pull request by wkloucek**
Done in this PR:
- Add arm32v7 and arm64v8
- remove EOL nodejs 11
- update latest nodejs to 15
- add nodejs 14 and 15
- base all on Ubuntu 18.04 LTS
- switch to opencontainers labels

### CODE REVIEW

**Comment by xoxys** [comment]
Can we switch to minimal opencontainers labels if you touch it anyway? https://github.com/owncloud-ci/asciidoctor/blob/master/latest/Dockerfile.amd64#L3

**Review by xoxys — APPROVED** [review]
Thank you!

**Comment by wkloucek** [comment]
@LukasHirt can you give me some background about https://github.com/owncloud-ci/nodejs/commit/9c66a2aa4ee071bc9a75460a4521e7752188e3c8 ? Why was this change needed?

**Comment by LukasHirt** [comment]
> can you give me some background about 9c66a2a ? Why was this change needed?

@wkloucek We needed to update the nodejs and since I was touching it I was asked to update also the ubuntu version. See https://github.com/owncloud-ci/nodejs/pull/7#pullrequestreview-556272297

One thing that I'd like to move forward some day soon - https://github.com/owncloud-ci/nodejs/pull/7#issuecomment-748904042

**Pull request merged**
